[package]
name = "Catick"
version = "0.1.0"
edition = "2024"

[dependencies]
x11rb = { version = "0.14.0", features = ["shape"] }
clap = { version = "4", features = ["derive"] }
rustix = { version = "1", features = ["event", "mm", "pipe", "time"] }
serde = { version = "1", features = ["derive"] }
toml = "1"
